### ISSUE TITLE
Hidden user account

### ISSUE THREAD

**Issue by Eitot** [aserper/osx.pirrit_removal#1]
I came across your blog post while I looked into a post at MacRumors. I am not entirely sure, but I think it is related to what you identify as OSX.Pirrit. However, that user also reported that a hidden user account was created. Is this something that you looked into as well?

http://forums.macrumors.com/threads/what-is-unillumination-process-mavericks.1966015/

**Comment by aserper** [comment]
Hi! Thanks for contacting me. This actually looks EXACTLY like Osx/Pirrit!
